### ISSUE TITLE
Runtime error related to docstrings

### ISSUE THREAD

**Issue by chuaxr** [psyplot/psyplot#26]
I encountered the following error when using psyplot-1.2.1 and docrep-0.3.1 in python3.8. The same error occurs when I try `psyplot -aV`.

```python
(work) chuaxr@elogin1:~$ psyplot
Traceback (most recent call last):
  File "/home/users/gov/nea/chuaxr/.conda/envs/work/bin/psyplot", line 7, in <module>
    from psyplot.__main__ import main
  File "/home/users/gov/nea/chuaxr/.conda/envs/work/lib/python3.8/site-packages/psyplot/__init__.py", line 7, in <module>
    from psyplot.config.rcsetup import rcParams
  File "/home/users/gov/nea/chuaxr/.conda/envs/work/lib/python3.8/site-packages/psyplot/config/__init__.py", line 13, in <module>
    from .rcsetup import psyplot_fname
  File "/home/users/gov/nea/chuaxr/.conda/envs/work/lib/python3.8/site-packages/psyplot/config/rcsetup.py", line 25, in <module>
    @docstrings.get_sectionsf('safe_list')
  File "/home/users/gov/nea/chuaxr/.conda/envs/work/lib/python3.8/site-packages/docrep/decorators.py", line 110, in deprecated
    return func(self, *args, **kwargs)
  File "/home/users/gov/nea/chuaxr/.conda/envs/work/lib/python3.8/site-packages/docrep/__init__.py", line 927, in get_sectionsf
    return self.get_sections(base=args[0], *args[1:], **kwargs)
TypeError: get_sections() missing 1 required positional argument: 's'

```

**Comment by Chilipp** [comment]
hi @chuaxr! thanks for reporting and my apologies for this issue! It's already resolved in the master branch of psyplot, so you can make it work if you update psyplot from the `psyplot/label/master` channel, e.g. `conda update -c psyplot/label/master --override-channels psyplot`. The same is True for `psy-simple`, `psy-maps`, and `psyplot-gui`.

I actually made a new build on conda-forge (see https://github.com/conda-forge/psyplot-feedstock/pull/10), but for some reason it still uses the previous build. Eventually I have to mark the old one as broken.

Anyway, I am working hard on making a new release and fixing the last bits and peaces of deprecation warnings with the latest version of matplotlib. I'll let you know when it is available on conda-forge

**Comment by chuaxr** [comment]
Thanks for letting me know, I was able to work around the issue by  creating a new environment for psyplot ( `conda create -n psy -c conda-forge psyplot`), which selected python 3.6.11 and docrep 0.2.7.
