### ISSUE TITLE
Installation issue in WinPython

### ISSUE THREAD

**Issue by xjlai** [psyplot/psyplot#48]
#### Code Sample, a copy-pastable example if possible

```python
import psyplot
import psyplot.project as psy
psy.plot.show_plot_methods()
```
#### Problem description

I worked in environmental fluid dynamics using the unstructured grids. Thanks to the great work in visualizing unstructured grid data. That is what I need in the future work.  

I am exciting to install  psyplot in the WinPython using  pip install or from source following the guide. It seems that I have successfully installed psyplot and its dependence, such as psy-map, psy-simple... But, I can not get the right module when I began to  test it. 
I tested psy.plot.show_plot_methods().  It shows empty. Also I can not get the method of "psy.plot.mapplot"
How can I overcome it?  Any help would be appreciated.

#### Expected Output
What should have been expected? You can hide large error messages within  ``<details></details>`` tags, e.g.

<details>
WARNING:psyplot.config.rcsetup:Failed to import EntryPoint(name='plugin', value='psy_maps.plugin', group='psyplot')!
WARNING:psyplot.config.rcsetup:Failed to import EntryPoint(name='plugin', value='psy_simple.plugin', group='psyplot')!
WARNING:psyplot:Could not import EntryPoint(name='plugin', value='psy_maps.plugin', group='psyplot')
Traceback (most recent call last):
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\psyplot-1.4.0+10.g26e477b-py3.9.egg\psyplot\__init__.py", line 146, in get_versions
    mod = ep.load()
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\importlib_metadata\__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\psy_maps\plugin.py", line 33, in <module>
    from psy_simple.plugin import (
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\psy_simple\plugin.py", line 41, in <module>
    from matplotlib.rcsetup import (
ImportError: cannot import name 'validate_legend_loc' from 'matplotlib.rcsetup' (D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\matplotlib\rcsetup.py)
WARNING:psyplot:Could not import EntryPoint(name='plugin', value='psy_simple.plugin', group='psyplot')
Traceback (most recent call last):
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\psyplot-1.4.0+10.g26e477b-py3.9.egg\psyplot\__init__.py", line 146, in get_versions
    mod = ep.load()
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\importlib_metadata\__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\psy_simple\plugin.py", line 41, in <module>
    from matplotlib.rcsetup import (
ImportError: cannot import name 'validate_legend_loc' from 'matplotlib.rcsetup' (D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\matplotlib\rcsetup.py)
</details>

#### Output of ``psyplot -aV``

<details>
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
WARNING:psyplot.config.rcsetup:Failed to import EntryPoint(name='plugin', value='psy_maps.plugin', group='psyplot')!
WARNING:psyplot.config.rcsetup:Failed to import EntryPoint(name='plugin', value='psy_simple.plugin', group='psyplot')!
WARNING:psyplot:Could not import EntryPoint(name='plugin', value='psy_maps.plugin', group='psyplot')
Traceback (most recent call last):
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\psyplot-1.4.0+10.g26e477b-py3.9.egg\psyplot\__init__.py", line 146, in get_versions
    mod = ep.load()
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\psy_maps\plugin.py", line 33, in <module>
    from psy_simple.plugin import (
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\psy_simple\plugin.py", line 41, in <module>
    from matplotlib.rcsetup import (
ImportError: cannot import name 'validate_legend_loc' from 'matplotlib.rcsetup' (D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\matplotlib\rcsetup.py)
WARNING:psyplot:Could not import EntryPoint(name='plugin', value='psy_simple.plugin', group='psyplot')
Traceback (most recent call last):
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\psyplot-1.4.0+10.g26e477b-py3.9.egg\psyplot\__init__.py", line 146, in get_versions
    mod = ep.load()
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\psy_simple\plugin.py", line 41, in <module>
    from matplotlib.rcsetup import (
ImportError: cannot import name 'validate_legend_loc' from 'matplotlib.rcsetup' (D:\Softs\WPy64-39100\python-3.9.10.amd64\lib\site-packages\matplotlib\rcsetup.py)
psyplot:
  requirements:
    matplotlib: 3.5.1
    numpy: 1.21.5
    pandas: 1.4.0
    python: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit
      (AMD64)]
    xarray: 0.20.2
  version: 1.4.0+10.g26e477b
psyplot_gui:
  requirements:
    pyqt: 5.15.1
    qt: 5.15.1
    qtconsole: 5.2.2
  version: 1.4.0

</details>

#### NOTE
This is a bug report.

For requesting new features, use [this template](https://github.com/psyplot/psyplot/issues/new?template=new_feature.md&title=NEW+FEATURE:).

For changing existing features, use [this template](https://github.com/psyplot/psyplot/issues/new?template=change_feature.md&title=CHANGE+FEATURE:).

**Comment by afurnish** [comment]
I am also new to psyplot for use with the output files from the Delft hydrodynamic models. I tried to install it yesterday and the same thing has occurred on my machines, both Windows and Linux running python via Spyder (Anaconda).  I also do not get anything from, "psy.plot.show_plot_methods()"

Some of the packages appear to be missing as you say. I tried to go through the unstructured data example and "psyplot.project.plot.mapplot" seems to not exist. 

The only options from "psyplot.project.plot." are;  deleter, fdel, fget, fset, getter and setter. I am looking through the source code but to no avail.

**Comment by Chilipp** [comment]
Hey @xjlai and @afurnish !

My apologies that you ran into this issue that should have been fixed quite some time ago but I desperately need to make the new release...

Anyway, seems to be a duplicate of #44. Could you please try the fix I mention there? I.e. use `matplotlib<3.5`?

**Comment by xjlai** [comment]
Thank you for your reply. I will try it.

**Comment by Chilipp** [comment]
hey @xjlai and @afurnish. This PR should now be closed as psy-simple has been made compatible (the package on conda-forge will be updated today). Feel free to reopen this issue if it does not work for you.
